$schema: ../../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: debug
  progress_display: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp" # Options: "timestamp" or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    pentest_tools:
      description: "Server with pentest tools"
      transport: streamable_http
      url: http://mcp-server:8000/mcp/

openai:
  default_model: "gpt-4.1-nano"